"""
Core Package
============

This package contains all the objects required for the simulation.
This is where you add new Xray sources if testing different sources.
You could add new Gamma sources, but you would probably
have to develop a new method to find_hits in the simulation
submodule.

Modules:
    - gamma: The Gamma pulse
    - simulation: The Monte Carlo simulation
    - xray: The Xray source
    - xray_lambertian: A lambertian xray source
    - xray_lambertian_Ge: Germanium lambertian xray source
    - xray_lambertian_Pd: Palladium lambertian xray source
    - xray_line: Line Xray source
    - xray_line_twave: Line Xray source generated by a travelling wave
"""