#!/bin/bash
#PBS -N g4beamline_d_analysis
#PBS -l select=1:ncpus=1:mem=1gb
#PBS -l walltime=2:00:00

cd $PBS_O_WORKDIR

module load gcc/11.2.0
module load root/6.26

export CC=/apps/gcc/11.2.0/bin/gcc
export CXX=/apps/gcc/11.2.0/bin/g++
export PATH=/apps/gcc/11.2.0/bin:$PATH
export LD_LIBRARY_PATH=/apps/gcc/11.2.0/lib64:/apps/gcc/11.2.0/lib:$LD_LIBRARY_PATH

python3 module_download.py
python3 g4bl_stuff/setup_analysis.py