"""
Data Analysis Package
=====================

This package contains the submodules for analysing the raw simulation data files.
This includes locating maximal positron yields, delay optimisation, and plotting features.

Modules:
    - optimise_delay: Performs analysis and statistics on the simulation data
    - plot_optimise_data: Plots the csv generated by optimise_delay
"""
