"""
Formula for the Breit Wheeler cross-section taken from
BKettle et al. A laser-plasma platform for photon-photon physics. 2018.
New J. Phys 23 115006 Section 8

Plot_formulae() is to compare with the plots generated by Cary Colgan in his PhD thesis.
"""
import matplotlib.pyplot as plt
import numpy as np
from matplotlib import cm

from theory import values     #pylint: disable=import-error

def dc_bw(root_s: list, theta: list) -> list:
    """Breit Wheeler differential cross section

    Args:
        root_s (np.ndarray[float]): centre of mass energy
        theta (np.ndarray[float]): Collision and scattering angle
    
    Returns:
        np.ndarray[float]: differential Briet Wheeler cross section (barns)
    """
    root_s = root_s * values.e * 1e6 #Convert out of MeV to SI
    s = root_s**2
    beta =  np.sqrt( 1 - 4 * values.m ** 2 * values.c ** 4 / s )

    d_cs = beta * values.re ** 2 * values.m ** 2 * values.c ** 4 / s  * (
        ( 1 + 2 * beta * np.sin(theta) ** 2 
        - beta ** 4 -beta ** 4 * np.sin(theta) ** 4 ) /
        ( 1- beta * beta * np.cos(theta) ** 2 ) ** 2)
    
    d_cs *= 1e28 #conversion to barns

    return d_cs

def c_bw(root_s: list) -> list:
    """Breit Wheeler total cross section

    Args:
        root_s (np.ndarray[float]): centre of mass energy
    
    Returns:
        np.ndarray[float]: Breit wheeler total cross section
    """
    # unit conversion #################################
    root_s = root_s * values.e * 1e6 #Convert out of MeV
    s_list = root_s**2

    # check if root_s is singular/float #############
    if isinstance(s_list, float):
        s_list = [s_list]

    c_bw_list = []

    for s in s_list:
        if  1 - 4 * values.m ** 2 * values.c ** 4 / s >= 0:
            beta =  np.sqrt( 1 - 4 * values.m ** 2 * values.c ** 4 / s )

            cs = np.pi * values.re ** 2 * ( 1 - beta * beta ) / 2 * (
                ( 3 - beta ** 4 ) * np.log( ( 1 + beta ) / ( 1 - beta ) )
                - 2 * beta * ( 2 - beta * beta )
            )

            cs *= 1e28 #conversion to barns
            c_bw_list.append(cs)
        
        else:
            cs = 0.0 #reaction doesn't happen
            c_bw_list.append(cs)

    return np.array(c_bw_list)


def plot_formulae():
    """
    Plots the formulae for the total breit wheeler and differential cross section
    """
    
    # setup figure ########################################################
    fig = plt.figure(figsize=plt.figaspect(0.5))

    ax1 = fig.add_subplot(1, 2, 1, projection='3d')
    ax1.view_init(elev=15, azim=60, roll=0)
    ax1.set_title('Differential Breit-Wheeler scattering cross-section')
    ax1.set_xlabel('$\\theta$(rad)')
    ax1.set_ylabel('$\\sqrt{s}$(MeV)')
    ax1.set_zlabel('$d\\sigma_{\\gamma\\gamma}/d\\Omega (b)$')

    ax2 = fig.add_subplot(1, 2, 2)
    ax2.set_title('Total Breit-Wheeler scattering cross-section')
    ax2.set_xlabel('$\\sqrt{s}$(MeV)')
    ax2.set_ylabel('$\\sigma_{\\gamma\\gamma}(b)$')
    ax2.set_xlim(1e-1, 1e3)

    # generate values ######################################################
    # differential cross section #############
    theta = np.linspace(0, np.pi, 100)
    root_s_differential = np.linspace(1, 5, 100)
    theta, root_s_differential = np.meshgrid(theta, root_s_differential) #for array dimensions

    diff_cross_sec = dc_bw(root_s_differential, theta)
    
    # total cross section ###################
    root_s = np.logspace(0, 3, 1000)
    cross_sec = c_bw(root_s)

    # plot values #########################################################
    ax1.plot_surface(theta, root_s_differential, diff_cross_sec, cmap = cm.gnuplot) #pylint: disable = no-member
    ax2.loglog(root_s, cross_sec, color='red')

    plt.show()